### ISSUE TITLE
Status bar on bottom

### ISSUE THREAD

**Issue by sfarzy** [caiogondim/maglev#15]
In my previous installation, it worked perfectly.

I reinstalled it with same instructions shown in the README. There were few isuues.

- status bar appears in the bottom instead of the usual top. 
-  Date and time on the left side of status bar are not clearly visible 
-  When new panes are created, Line separating them are  only partially visible.

![tmux](https://cloud.githubusercontent.com/assets/10276208/11606263/40e82692-9b41-11e5-8deb-70a9cd17f1bd.png)

**Comment by caiogondim** [comment]
There was a major rewrite.
Please follow the new README instructions.

<img width="951" alt="screen shot 2015-12-07 at 11 35 24" src="https://cloud.githubusercontent.com/assets/33044/11624818/acdeef52-9cd6-11e5-9394-1ffaffc69afc.png">

Let me know if you still have some issues, so i can help you out and close the issue.

Cheers.

**Comment by sfarzy** [comment]
Followed the README and this is my ```.tmux.conf``` . The problem still persists.

![image](https://cloud.githubusercontent.com/assets/10276208/11677035/22907944-9e5f-11e5-9c32-110b056771b5.png)

![image](https://cloud.githubusercontent.com/assets/10276208/11677063/786fe9da-9e5f-11e5-952f-2868347167f8.png)

**Comment by caiogondim** [comment]
You have to source the modified `tmux.conf` or open a new tab so tmux can read the new `tmux.conf`.
You did this as well?

**Comment by sfarzy** [comment]
Yes. Already did that and no change.

**Comment by caiogondim** [comment]
Ok. Will investigate.
Thanks for the report.

**Comment by paanvaannd** [comment]
I came here to report the same issue. Using a Mac running OS X 10.11 (El Capitan) on iTerm2. I installed this theme using the method outlined in the README and am having all the same issues reported by @sfarzy.

In addition to what was reported, when using the 'tmux source .tmux.conf' command within a running tmux session, the right side of the status bar displays properly (as in, the CPU and Battery indicators show proper information and are properly formatted, though the bar is still on the bottom) for about half a second or less, and then it reverts to how the images posted in this thread look again. Every time I run the command, the same flicker of information appears, then collapses again.

**Comment by hermeszr** [comment]
I decided to delve into tmux style configuration, and figured out things were a bit off with the theme (Perhaps this is due a tmux version change...?)

Anyway, I've cloned the repo and fixed my theme to look like the picture seen in `README.md`. Enjoy!
https://github.com/hermeszr/maglev/commit/d5e9cbe48ac873dbbd34e68ad13007d02bc2d4a1

**Comment by paanvaannd** [comment]
Thanks for the edits @hermeszr! Unfortunately, not much has changed in the tmux layout. I have changed my font used (both regular and non-ASCII) to InputMono regular, which is Powerline compatible. Furthermore, I have turned off any transparency and blurring effects I previously had, set character encoding to Unicode (UTF-8), terminal type to xterm-256color, and removed all preferences from my tmux config file but for the modified key binding preference, list of plugins (which is exactly the list of plugins on maglev's README.md), initializing TPM, and `set -g default-terminal 'screen-256color`, just to be sure. I renamed the maglev.tmux within my .tmux/plugins/maglev directory to something else and copied your edited version there, retaining the maglev.tmux name to make sure that is what is sourced by TPM. I ran <prefix> + I again to make sure maglev is installed and used `tmux source .tmux.conf` again after all of these changes.

Result: the status bar is at the top of the screen now (thank you!) but other than that, this is what the layout looks like:
<img width="960" alt="tmux-status-bar-issue1" src="https://cloud.githubusercontent.com/assets/16567134/12249078/233a2e06-b883-11e5-8db3-c53b79339eea.png">
The CPU and Battery information pops up, as before, for about half a second after sourcing .tmux.conf but after half a second it is replaced by the bar as it is shown in the above screenshot. The time and date are there, just not visible unless highlighted:
<img width="960" alt="tmux-status-bar-issue2" src="https://cloud.githubusercontent.com/assets/16567134/12249084/327cd4a4-b883-11e5-817d-a8f2ba738f79.png">

Here are all relevant iTerm2 preferences:
<img width="924" alt="iterm-colors" src="https://cloud.githubusercontent.com/assets/16567134/12249264/48ec77ac-b884-11e5-937a-5fa20a2fc55f.png">
<img width="924" alt="iterm-text" src="https://cloud.githubusercontent.com/assets/16567134/12249268/4a91d80e-b884-11e5-80c1-8d4d2a316a91.png">
<img width="924" alt="iterm-window" src="https://cloud.githubusercontent.com/assets/16567134/12249271/4c3172b4-b884-11e5-9ab9-29449a1a18bf.png">
<img width="924" alt="iterm-terminal" src="https://cloud.githubusercontent.com/assets/16567134/12249273/4e434faa-b884-11e5-857d-a4ace13923cd.png">

Sorry if this is too much information for addressing this issue, I'm just confused as to what is happening with my setup that there are so many issues with tmux+maglev. Thank you for your work so far, and please let me know if there is any more information you would need in order to figure out what is going wrong!

**Comment by caiogondim** [comment]
Just improved the README with conf for putting the status bar on top.

**Comment by hermeszr** [comment]
@paanvaannd @caiogondim I now realized that my PR may fit my needs but it lacks global support. I think the main issue is with how specific terminals define color
themes, and my fix was rather specific to my definitions of colors... tl;dr I think I can rewrite the theme so it would work globally, I'll do so and commit the change. @paanvaannd, I'll be in touch with you to see whether the commit I'll add will work. I don't know if the CPU and battery issue is related to the other colors issues, will look into it.

**Comment by caiogondim** [comment]
@hermeszr As a good practice, we should respect the themes each one is using. And your PR doesn't fix the CPU and Battery segments. I already fixed it before using tmux plugins, will fix it again. Hold on =)

**Comment by paanvaannd** [comment]
@caiogondim @hermeszr Sure thing, and thank you both for the assistance! I would be glad to test it out as soon as I can, though I am having trouble with tmux in general now with it simply not launching at all. I've reported the issue in tmux's git of course, but just wanted to let you know that it may be a while before I can test any edits once they are made.

**Comment by marzk** [comment]
@paanvaannd I have the same issue with u, using  OS X 10.11 with iTerm2. i have a temporary solution to solve the CPU and battery issue. u can put the `'caiogondim/maglev'` line in front of the `'tmux-plugins/tmux-battery'` and `'tmux-plugins/tmux-cpu'` line.

```bash
# just change the order, but it will cause a problem which has a unformat text before transform
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'caiogondim/maglev'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
```
(My English is poor...)

**Comment by caiogondim** [comment]
@marzk This actually fixed the problem for me! Amazing.

**Comment by caiogondim** [comment]
New **Installing** instructions were updated https://github.com/caiogondim/maglev#installing

**Comment by sfarzy** [comment]
Thank you @caiogondim @marzk for the solution. It indeed solved the status bar problems.
But, Partial lines between panes still exists. Does it has to do anything with other dependencies ?

**Comment by paanvaannd** [comment]
Thank you both so much, @caiogondim and @marzk, that worked perfectly! As stated by @sfarzy there are still some lines between panes but I'm glad I can use maglev now :)
