### ISSUE TITLE
Status bar is black and therefore useless

### ISSUE THREAD

**Issue by tonekk** [caiogondim/maglev#17]
Hi,

I just installed your plugin today, because I really like its design.
Sadly it looks like this on my machine:

<img width="1440" alt="screen shot 2016-01-11 at 19 33 11" src="https://cloud.githubusercontent.com/assets/3327396/12242593/532301bc-b89a-11e5-8fac-a5906338aa28.png">

**Comment by hermeszr** [comment]
I decided to delve into tmux style configuration, and figured out things were a bit off with the theme (Perhaps this is due a tmux version change...?)

Anyway, I've cloned the repo and fixed my theme to look like the picture seen in `README.md`. Enjoy!
https://github.com/hermeszr/maglev/commit/d5e9cbe48ac873dbbd34e68ad13007d02bc2d4a1

**Comment by paanvaannd** [comment]
@tonekk I've had the same issue with mine, even after using @hermeszr's edited `maglev.tmux` file, though his revisions did move the bar to the top of the window as it was supposed to. Perhaps this has something to do with iTerm2 preferences instead of the config files? I was able to bring out a bit of the color that was hidden, like the text that displays the date and time, by changing the `minimum contrast` setting within iTerm2's preference pane like so:
![contrast](https://cloud.githubusercontent.com/assets/16567134/12254053/5eff3252-b8aa-11e5-9959-8bb244e22367.png)

Unfortunately, I think this is just a band-aid patch considering any value less than this will bring the text back into obscurity and any value more than this starts to change the colors of the graphics (arrows, blocks, etc.) such that it messes with the whole theme.

**Comment by caiogondim** [comment]
Sorry for being absent here.

There was a major rewrite of the theme. We are now using tmux plugins, and there is no `.tmux.conf` rewrite. The code is much better, thanks to @faceleg for the amazing work. But with this, it seems some erros came as well.

I will take a look on this, and fix the bugs, for it to behave as explained on README.

@hermeszr Please, open a PR if you have a fix for the project. I only have my free time to work on, so every help is much appreciated.

I'm aware of this issue, and we already have a duplicate issue on https://github.com/caiogondim/maglev/issues/15

Are you ok on closing this issues and focusing on the older one?

**Comment by caiogondim** [comment]
As suggested by @marzk, just put `'caiogondim/maglev'` as the second item on `.tmux.conf`
```
# List of plugins
set -g @tpm_plugins '                \
    caiogondim/maglev                \
    tmux-plugins/tpm                 \
    tmux-plugins/tmux-sensible       \
    tmux-plugins/tmux-resurrect      \
    tmux-plugins/tmux-continuum      \
    tmux-plugins/tmux-yank           \
    tmux-plugins/tmux-pain-control   \
    tmux-plugins/tmux-copycat        \
    tmux-plugins/tmux-open           \
    tmux-plugins/tmux-battery        \
    tmux-plugins/tmux-cpu            \
'
```

New **Installing** instructions were updated https://github.com/caiogondim/maglev#installing

**Comment by caiogondim** [comment]
Please, close the issue if the problem was solved.

**Comment by yifanchen** [comment]
nice, this worked. I used to have CPU and Battary at very bottom. I just verifed and revmoed those from bottom.

**Comment by caiogondim** [comment]
Closing the issue.

**Comment by abi93k** [comment]
I'm still facing this issue. Does anyone have a proper fix ? 
<img width="1280" alt="screen shot 2017-06-14 at 10 02 47 pm" src="https://user-images.githubusercontent.com/2098233/27166116-56da9ec6-514d-11e7-8bd2-8ded770ded02.png">
